### PR TITLE
Add code generators section in other resources with initializr and bootify

### PR DESCRIPTION
**Pull request by tleipzig**
Hello,
how about adding a "code generators" section under others? Spring Initializr is a must-know for Spring Boot developers I guess, and Bootify can be useful as well if you work with a relational database.

### CODE REVIEW

**Comment by tleipzig** [comment]
Is there any update on the issue?:)

**Comment by ThomasVitale** [comment]
@tleipzig Thanks for your contribution and sorry for the late answer. Could you list the two items alphabetically? Also, what do you think about changing the title of the section to "Project Scaffolding"?

**Comment by tleipzig** [comment]
Thank you @ThomasVitale - Scaffolding is more precise indeed! Applied your suggestions.

**Comment by ThomasVitale** [comment]
Thank you!

**Comment by tleipzig** [comment]
Thanks a lot!

**Pull request merged**
